version: '3.7'

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /opt/homeassistant/config:/config 
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - 80:8123

  zwavejs2mqtt:
    image: zwavejs/zwavejs2mqtt:latest 
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
